### ISSUE TITLE
Chat Hyperlinks for Poss, Up, Hero, Drama, and +3 Do not work

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#193]
Error: Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at renderSkillChat (torgchecks.js:567:25)
    at HTMLAnchorElement.onPossibility (chat.js:41:5)
    at HTMLElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)

**Comment by gmmatt** [comment]
Fixed in v10-compatibility branch

Now passing actors by ID instead of data element.
