### ISSUE TITLE
Can't deal cards

### ISSUE THREAD

**Issue by SwordofSpirit** [MetaMorphic-Digital/torgeternity#266]
Players can click the button to draw cards, but if I attempt to deal cards from the deck, I get this:

`commons.js:2004 Error: You are accessing the Card#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1993:19)
    at Card._logV10CompatibilityWarning (commons.js:8450:14)
    at get data [as data] (commons.js:8338:24)
    at lookupProperty (handlebars.min.js:27:16153)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:31:259)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at Object.<anonymous> (handlebars.min.js:27:7289)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:65:49)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:7661:10)
    at async torgeternityDeck._renderInner (foundry.js:5895:16)
    at async torgeternityDeck._renderInner (foundry.js:6463:18)
    at async torgeternityDeck._render (foundry.js:5740:19)
    at async torgeternityDeck._render (foundry.js:6452:5)`

**Comment by Algor0113** [comment]
@SwordofSpirit 
I cannot reproduce it, it works fine with me. Is this still an issue?

**Comment by Durak-Git** [comment]
No, it was just a warning
I think I already removed the "data" reference at some point
